blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from blog.apps import NewappConfig
from blog.views import (ArticleCreateView, ArticleDetailView, BaseArticleListView,
                        ArticleListView, ArticleUpdateView, ArticleDeleteView)
app_name = NewappConfig.name

urlpatterns = [
    path('article_list/', ArticleListView.as_view(), name='article_list'),
    path('base_article_template/', BaseArticleListView.as_view(), name='base_template'),
    path('article_form/<int:pk>/', ArticleDetailView.as_view(), name='article_form'),
    path('article_form_create/', ArticleCreateView.as_view(), name='article_form_create'),
    path('article_update/<int:pk>/update/', ArticleUpdateView.as_view(), name='article_update'),
    path('article_delete/<int:pk>/', ArticleDeleteView.as_view(), name='article_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from datetime import datetime
from django.db import models


class Article(models.Model):

    title = models.CharField(
        max_length=80, verbose_name='Название статьи', help_text='Введите название статьи'
    )

    short_descr = models.CharField(max_length=200, verbose_name='Краткое содержание статьи, до 200 симвл.',
        help_text='Введите краткое содержание статьи')

    content = models.TextField(max_length=8000, verbose_name='Содержимое статьи', help_text='Напишите сюда '
                                                                     'свою статью')

    preview = models.ImageField(upload_to='images/', verbose_name='Превью изображения')

    created_at = models.DateField(auto_now_add=True, verbose_name='Дата публикации')
    updated_at = models.DateField(auto_now=True)

    is_published = models.BooleanField(
        verbose_name='Признак публикации',
        default=False
    )

    number_of_views = models.IntegerField()


    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

    def __str__(self):
        return f'Статья "{self.title}" от {self.created_at}'

blog/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView, TemplateView
from blog.models import Article
from django.urls import *


class BaseArticleListView(ListView):
    model = Article
    template_name = 'base_article_template.html'


class ArticleListView(ListView):
    model = Article
    template_name = 'article_list.html'
    context_object_name = 'articles'

    def get_queryset(self):
        return Article.objects.filter(is_published=True)


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'article_form.html'

    def get_object(self):
        obj = super().get_object()
        obj.number_of_views += 1
        obj.save()
        return obj

class ArticleCreateView(CreateView):
    model = Article
    fields = ('title', 'short_descr', 'content', 'preview', 'is_published', 'number_of_views')
    template_name = 'article_form_create.html'
    success_url = reverse_lazy('blog:article_list')


class ArticleUpdateView(UpdateView):
    model = Article
    fields = ('title', 'short_descr', 'content', 'preview', 'is_published')
    template_name = 'article_update.html'

    def get_success_url(self):
        return reverse('blog:article_form', kwargs={'pk': self.object.pk})


class ArticleDeleteView(DeleteView):
    model = Article
    template_name = 'article_delete.html'
    success_url = reverse_lazy('blog:article_list')

blog/templates/article_delete.html
{% extends 'base_article_template.html' %}
{% block content %}

<div class="container">
  <div class="row">
    <div class="col">
      <form class="row" method="post" enctype="multipart/form-data">
        <div class="card">
             <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
             </div>
            <div class="col">
        <div class="card shadow-sm">
            <div class="card-body">
                <h1 class="card-title">{{ article.title }}</h1>
                <h3 class="card-title">{{ article.short_descr | truncatechars:100 }}</h3>
                <p class="card-text">Дата публикации: {{ article.created_at }}</p>
                <p class="card-text">Дата последней редакции: {{ article.updated_at }}</p>
                <p class="card-text">{{ article.content }}</p>
                <div class="d-flex justify-content-between align-items-center">
                </div>
            </div>
        </div>
    </div>
            <h3>Точно удалить статью?</h3>
            <button type="submit" class="btn btn-danger">Да, точно удалить</button>
            <a class="btn btn-secondary" href="{% url 'blog:article_list' %}" role="button">Отмена</a>

        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/article_form.html
{% extends 'base_article_template.html' %}
{% block content %}

<div class="container">
  <div class="row">
    <div class="col">
      <form class="row" method="post" enctype="multipart/form-data">
        <div class="card">
             <div class="card-body">
                {% csrf_token %}
                {{ form.as_p}}
             </div>
            <div class="col">
        <div class="card shadow-sm">
            <img src="{{ article.preview.url }}" class="card-img-top" alt="{{ article.title }}">
            <div class="card-body">
                <h1 class="card-title">{{ article.title }}</h1>
                <h3 class="card-title">{{ article.short_descr | truncatechars:100 }}</h3>
                <p class="card-text">Дата публикации: {{ article.created_at }}</p>
                <p class="card-text">Дата последней редакции: {{ article.updated_at }}</p>
                <p class="card-text">Просмотров: {{ article.number_of_views }}</p>
                <p class="card-text">{{ article.content }}</p>
                <div class="d-flex justify-content-between align-items-center">
                </div>
            </div>
        </div>
    </div>
            <a class="btn btn-primary" href="{% url 'blog:article_update' article.pk %}" role="button">Редактировать статью</a>
            <a class="btn btn-danger" href="{% url 'blog:article_delete' article.pk %}" role="button">Удалить статью</a>
            <a class="btn btn-primary" href="{% url 'blog:article_list'%}" role="button">К списку статей</a>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/article_form_create.html
{% extends 'base_article_template.html' %}
{% block content %}

<div class="container">
  <div class="row">
    <div class="col">
      <form class="row" method="post" enctype="multipart/form-data">
        <div class="card">
             <div class="card-body">
                {% csrf_token %}
                {{ form.as_p}}
             </div>
            <button type="submit" class="btn btn-primary">
              Создать статью
            </button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/article_list.html
{% extends 'base_article_template.html' %}
{% block content %}

<div class="row row-cols-1>
    {% for article in articles %}
        <div class="col">
            <div class="card shadow-sm">
                <div class="card-body">
                    <h1 class="card-title">{{ article.title }}</h1>
                    <h3 class="card-title">{{ article.short_descr | truncatechars:100 }}</h3>
                    <p class="card-text">Дата публикации: {{ article.created_at }}</p>
                    <p class="card-text">Дата последней редакции: {{ article.updated_at }}</p>
                    <p class="card-text">{{ article.content }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                        <a class="btn btn-primary" href="{% url 'blog:article_form' article.pk %}" role="button">Посмотреть статью</a>
                        <a class="btn btn-primary" href="{% url 'blog:article_update' article.pk %}" role="button">Редактировать статью</a>
                        <a class="btn btn-primary" href="{% url 'blog:article_delete' article.pk %}" role="button">Удалить статью</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

blog/templates/article_update.html
{% extends 'base_article_template.html' %}
{% block content %}

<div class="container">
  <div class="row">
    <div class="col">
      <form class="row" method="post" enctype="multipart/form-data">
        <div class="card">
             <div class="card-body">
                {% csrf_token %}
                {{ form.as_p}}
             </div>
            <div class="col">

    </div>
            <button type="submit" class="btn btn-primary">
              Сохранить
            </button>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

blog/templates/base_article_template.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.145.0">
    <title>Album example · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.3/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#712cf9">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .bi {
        width: 1em;
        height: 1em;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }
    </style>


  </head>
  <body>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
  <symbol id="check2" viewBox="0 0 16 16">
    <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
  </symbol>
  <symbol id="circle-half" viewBox="0 0 16 16">
    <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
  </symbol>
  <symbol id="moon-stars-fill" viewBox="0 0 16 16">
    <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
    <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
  </symbol>
  <symbol id="sun-fill" viewBox="0 0 16 16">
    <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
  </symbol>
</svg>


    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
      <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
        id="bd-theme"
        type="button"
        aria-expanded="false"
        data-bs-toggle="dropdown"

        aria-label="Toggle theme (auto)">
  <svg class="bi my-1 theme-icon-active" aria-hidden="true"><use href="#circle-half"></use></svg>
  <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
</button>
<ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
  <li>
    <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light" aria-pressed="false">
      <svg class="bi me-2 opacity-50" aria-hidden="true"><use href="#sun-fill"></use></svg>
      Light
      <svg class="bi ms-auto d-none" aria-hidden="true"><use href="#check2"></use></svg>
    </button>
  </li>
  <li>
    <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark" aria-pressed="false">
      <svg class="bi me-2 opacity-50" aria-hidden="true"><use href="#moon-stars-fill"></use></svg>
      Dark
      <svg class="bi ms-auto d-none" aria-hidden="true"><use href="#check2"></use></svg>
    </button>
  </li>
  <li>
    <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto" aria-pressed="true">
      <svg class="bi me-2 opacity-50" aria-hidden="true"><use href="#circle-half"></use></svg>
      Auto
      <svg class="bi ms-auto d-none" aria-hidden="true"><use href="#check2"></use></svg>
    </button>
  </li>
</ul>

    </div>


<header data-bs-theme="dark">
  <div class="collapse text-bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4>О компании</h4>
          <p class="text-body-secondary">Статьи на разные темы. Пишите, что хотите! И без цензуры.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4>Связаться с нами</h4>
          <ul class="list-unstyled">
            <li><a href="#" class="text-white">Подписаться на нас в X</a></li>
            <li><a href="#" class="text-white">Подписатья на нас в Facebook</a></li>
            <li><a href="#" class="text-white">Отправить эл. письмо</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>Блог. Статьи на разные темы</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>

<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Библиотека умных мыслей</h1>
        <p class="lead text-body-secondary">Здесь мысли соревнуются за право быть самой умной.</p>
        <p>
          <a class="btn btn-primary" href="{% url 'blog:article_form_create' %}" role="button">Создать статью</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-body-tertiary">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </div>

</main>

<footer class="text-body-secondary py-5">
  <div class="container">
    <p class="float-end mb-1">
      <a href="#">Back to top</a>
    </p>
    <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
    <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a href="/docs/5.3/getting-started/introduction/">getting started guide</a>.</p>
  </div>
</footer>
<script defer src="/docs/5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq"></script>

    </body>
</html>