blog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from blog.apps import NewappConfig
from blog.views import (ArticleCreateView, ArticleDetailView, BaseArticleListView,
                        ArticleListView, ArticleUpdateView, ArticleDeleteView)
app_name = NewappConfig.name

urlpatterns = [
    path('article_list/', ArticleListView.as_view(), name='article_list'),
    path('base_article_template/', BaseArticleListView.as_view(), name='base_template'),
    path('article_form/<int:pk>/', ArticleDetailView.as_view(), name='article_form'),
    path('article_form_create/', ArticleCreateView.as_view(), name='article_form_create'),
    path('article_update/<int:pk>/update/', ArticleUpdateView.as_view(), name='article_update'),
    path('article_delete/<int:pk>/', ArticleDeleteView.as_view(), name='article_delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import path
from catalog.apps import NewappConfig
from django.conf import settings
from django.conf.urls.static import static
from catalog.views import (ContactDetailsTemplateView, HomeTemplateView, ProductDetailView, ProdDetFromBaseDetailView,
                           ProductListView, UpperMenuListView, ProdDetFromBaseCreateView, ProductUpdateView,
                           ProductDeleteView)

app_name = NewappConfig.name

app_name = 'catalog'


urlpatterns = [
    path('contacts/', ContactDetailsTemplateView.as_view(), name='contact_details'),
    path('home/', HomeTemplateView.as_view(), name='home'),
    path('product_details/<int:pk>/', ProductDetailView.as_view(), name='product_details'),
    path('prod_det_from_base/<int:pk>/', ProdDetFromBaseDetailView.as_view(), name='prod_det_from_base'),
    path('main/', ProductListView.as_view(), name='main'),
    path('upper_menu_subtempl/', UpperMenuListView.as_view(), name='upper_menu_subtempl'),
    path('prod_det_from_base_create/', ProdDetFromBaseCreateView.as_view(), name='prod_det_from_base_create'),
    path('product_update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('product_delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from users.apps import UsersConfig
from users.views import UserCreateView

app_name = UsersConfig.name

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html', form_class=AuthenticationForm), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
]

catalog/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(
        max_length=80, verbose_name="Название категории", help_text="Введите название категории"
    )
    description = models.CharField(
        max_length=150,
        verbose_name="Описание",
        help_text="Введите описание категории",
        blank=True,
        null=True,
    )

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(
        max_length=80, verbose_name="Продукт"
    )
    description = models.CharField(
        max_length=150,
        verbose_name="Описание",
        blank=True,
        null=True,
    )
    image = models.ImageField(
        upload_to="catalog/photos",
        blank=True,
        null=True,
    )
    category = models.ForeignKey(to=Category, on_delete=models.SET_NULL,
        max_length=50, verbose_name="Категория продукта", related_name='products', null=True,
                                 blank=True
    )
    purchase_price = models.FloatField(
        verbose_name="Цена"
    )
    created_at = models.DateField(
        auto_now=True,
        verbose_name="Дата создания", help_text="Укажите дату создания товара"
    )
    updated_at = models.DateField(
        auto_now=True,
        verbose_name="Дата изменения",
        help_text="Укажите дату создания товара"
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
        ordering = ["name"]

    def __str__(self):
        return self.name

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError
from catalog.models import Product

# создаем форму для ввода (создания) продукта
class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ['name', 'description', 'category', 'image', 'purchase_price']

    def __init__(self, *args, stop_words=None, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.stop_words = stop_words if stop_words is not None else []

        #настройка атрибутов виджета для полей формы
        self.fields['name'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Введите навание продукта'})

        self.fields['description'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Введите описание продукта'})

        self.fields['purchase_price'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Укажите цену продукта'})

    # определяем stop-слова для полей формы name и description
    # stop_words: list = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно',
    #                         'обман', 'полиция', 'радар']

    def clean_purchase_price(self):
        purchase_price: float = float(self.cleaned_data.get('purchase_price'))

        if purchase_price < 0:
            raise ValidationError(f'Неверный ввод цены "{purchase_price}". Цена должна быть больше или равна 0.')
        return purchase_price


    def clean_name(self):
        name: str = self.cleaned_data['name']

        for word in name.lower().split():
            if word in self.stop_words:
                raise ValidationError(f'Слово "{word}" не допускается ко вводу в названии')
        return name

    def clean_description(self):
        description: str = self.cleaned_data['description']

        for word in description.lower().split():
            if word in self.stop_words:
                raise ValidationError(f'Слово "{word}" не допускается ко вводу в описании товара')
        return description

# создадим специальную форму для удаления продукта(ов), поскольку в шаблоне нам не нужны поля для
# редактирования информации по продукту и созданию новых продуктов

class ProductFormDelete(forms.ModelForm):
    class Meta:
        model = Product
        fields = []

catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import DetailView, TemplateView, ListView, UpdateView, DeleteView, CreateView
from catalog.models import Product
from catalog.forms import ProductForm, ProductFormDelete
from django.urls import reverse_lazy

# инициализируем переменную со списком стоп-слов, чтобы использовать ее при создании формы
stop_words: list = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно',
                            'обман', 'полиция', 'радар']


class HomeTemplateView(TemplateView):
    template_name = 'home.html'


class ContactDetailsTemplateView(TemplateView):
    template_name = 'contact_details.html'


class ProductDetailView(DetailView):
    model = Product
    template_name = 'product_details.html'


class ProdDetFromBaseDetailView(DetailView):
    model = Product
    template_name = 'prod_det_from_base.html'

#контроллер почти тот же самый, то есть, ProdDetFromBaseCreateView, с использованием формы, для создания
# продукта:
class ProdDetFromBaseCreateView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'prod_det_from_base_create.html'
    success_url = reverse_lazy('catalog:main')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['stop_words'] = stop_words  # передаем список stop_words в форму
        return kwargs

#пишем контроллер для обновления информации по продукту
class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'product_update.html' #сделать новый шаблон для редактирования продукта
    success_url = reverse_lazy('catalog:main')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['stop_words'] = stop_words  # передаем список stop_words в форму
        return kwargs

#пишу контроллер для удаления продукта
# class ProductDeleteView(DeleteView):
#     model = Product
#     form_class = ProductForm
#     template_name = 'product_delete.html'  # сделать новый шаблон для удаления продукта
#     success_url = reverse_lazy('catalog:main')

class ProductDeleteView(DeleteView):
    model = Product
    form_class = ProductFormDelete
    template_name = 'product_delete.html'  # сделать новый шаблон для удаления продукта
    success_url = reverse_lazy('catalog:main')


class ProductListView(ListView):
    model = Product
    template_name = 'main.html'
    context_object_name = 'products'


class UpperMenuListView(ListView):
    model = Product
    template_name = 'upper_menu_subtempl.html'
    context_object_name = 'products'

catalog/templates/base_template.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.145.0">
    <title>Album example · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.3/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#712cf9">


    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }

        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }

        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }

        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }

        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
          z-index: 1500;
        }

        .bd-mode-toggle .bi {
          width: 1em;
          height: 1em;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }
    </style>


</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>


<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"

            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" aria-hidden="true">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" aria-hidden="true">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" aria-hidden="true">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>

</div>


<header data-bs-theme="dark">
    <div class="collapse text-bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4>О компании</h4>
                    <p class="text-body-secondary">Это компания "Всё для всего". Мы делаем всё для всего, и даже то, что
                        делать не нужно.</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4>Связаться с нами</h4>
                    <ul class="list-unstyled">
                        <li><a href="#" class="text-white">Подписаться на нас в X</a></li>
                        <li><a href="#" class="text-white">Отправить эл. письмо</a></li>
                        {% if user.is_authenticated %}
                        <form method="post" action="{% url 'users:logout' %}" style="display: inline;">
                            {% csrf_token %}
                            <button type="submit" class="text-blue"
                                    style="background: none; border: none; padding: 0; color: inherit; text-decoration: underline; cursor: pointer;">
                                Выход
                            </button>
                        </form>

                        {% else %}
                        <li><a href="{% url 'users:register' %}" class="text-blue">Регистрация</a></li>
                        <li><a href="{% url 'users:login' %}" class="text-blue">Вход</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                     viewBox="0 0 24 24">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                    <circle cx="12" cy="13" r="4"/>
                </svg>
                <strong>Просто альбом</strong>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Магазин "Всё для всего"</h1>
                <p class="lead text-body-secondary">Здесь есть всё для всего и даже больше.</p>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-body-tertiary">
        <div class="container">

            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

</main>

<footer class="text-body-secondary py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Back to top</a>
        </p>
        <p class="mb-1">Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p class="mb-0">New to Bootstrap? <a href="/">Visit the homepage</a> or read our <a
                href="/docs/5.3/getting-started/introduction/">getting started guide</a>.</p>
    </div>
</footer>
<script defer src="/docs/5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq"></script>

</body>
</html>

catalog/templates/contact_details.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <!-- Подключите статичеcкие файлы со стилями Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="/">Каталог</a>
        <a class="p-2 btn btn-outline-primary" href="/contacts/">Контакты</a>
    </nav>
</div>

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>

<!-- Подключите статичеcкие файлы со скриптами Bootstrap -->
</body>
</html>

catalog/templates/main.html
{% extends 'base_template.html' %}

{% block content %}

{% for product in products %}
<div class="col">
    <div class="card shadow-sm">
        <div class="card-body">
            <h3 class="card-text">{{ product.name }}</h3>
            <p class="card-text">{{ product.description|truncatechars:100 }}</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">

                    <a class="btn btn-primary" href="{% url 'catalog:product_details' product.pk %}" role="button">Показать</a>
                    <a class="btn btn-secondary" href="{% url 'catalog:product_update' product.pk %}" role="button">Редактировать</a>
                    <a class="btn btn-danger" href="{% url 'catalog:product_delete' product.pk %}"
                       role="button">Удалить</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

catalog/templates/prod_det_from_base.html
{% extends 'base_template.html' %}

{% block content %}

<div class="col">
  <div class="card shadow-sm">
    <div class="card-body">
      <p>Информация о товаре</p>
      <h2>{{ product.name }}</h2>
      <p class="card-text">{{ product.description }}</p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <button type="button" class="btn btn-sm btn-outline-secondary">Показать</button>
          <button type="button" class="btn btn-sm btn-outline-secondary">Редактировать</button>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}